# Generated by Django 3.2.6 on 2021-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor_paid',
            field=models.BooleanField(default=True),
        ),
    ]
