# Generated by Django 3.2.6 on 2021-09-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
